'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WhoseShoutPrime

    Partial Public Class CoffeeDate
        Public Property Id As Integer
        Public Property Shouter As Integer
        Public Property [Date] As Date
        Public Property Time As System.TimeSpan
        Public Property Venue As String
        Public Property Cost As Nullable(Of Decimal)
    
        Public Overridable Property User As User
    
    End Class

End Namespace
