'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WhoseShoutPrime

    Partial Public Class User
        Public Property Id As Integer
        Public Property UserName As String
        Public Property Password As String
        Public Property Authenticated As Boolean
    
        Public Overridable Property CoffeeDates As ICollection(Of CoffeeDate) = New HashSet(Of CoffeeDate)
    
    End Class

End Namespace
